apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
  labels:
    app: chat
    keel.sh/trigger: poll
    keel.sh/policy: "force"
    keel.sh/match-tag: "true"
  annotations:
    keel.sh/pollSchedule: "@every 1m"
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: chat
          image: sakthiratnam/fastapichat:latest
          imagePullPolicy: Always            
          ports:
            - containerPort: 80