apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
  labels:
    name: "chat"
  namespace: default
  annotations:
    keel.sh/policy: all
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: chat
          image: sakthiratnam/fastapichat:latest
          imagePullPolicy: Always            
          ports:
            - containerPort: 80