apiVersion: v1
kind: Service
metadata:
  name: clinto-chat
  labels:
    app: chat
spec:
  type: NodePort
  selector:
    app: chat
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30001
  